### ISSUE TITLE
Lockdown doesn't play well with express.Router()

### ISSUE THREAD

**Issue by mxpv** [thomseddon/node-oauth2-server#189]
Hi. It looks like lockdown pattern doesn't work when using express.Router()
I have added some tests which proves my theory https://github.com/mxpv/node-oauth2-server/commit/77555da99d3b5ae683cdc2db4e0abb5954bda025

Currently I'm getting:
```
 2 failing

  1) Lockdown pattern with router should correctly bypass:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (D:\GitHub\node-oauth2-server\node_modules\mocha\lib\runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2) Lockdown pattern with router should insert authorise by default:
     Error: expected body 'Hello' to match /access token was not found/i
      at error (D:\GitHub\node-oauth2-server\node_modules\supertest\lib\test.js:235:13)
      at Test.assert (D:\GitHub\node-oauth2-server\node_modules\supertest\lib\test.js:177:23)
      at Server.assert (D:\GitHub\node-oauth2-server\node_modules\supertest\lib\test.js:132:12)
      at Server.g (events.js:180:16)
      at Server.emit (events.js:92:17)
      at net.js:1277:10
      at process._tickCallback (node.js:442:13)

```

**Comment by thomseddon** [comment]
Ah is that something new? Would you mind having a peak at the code to see how we may fix it?

**Comment by thomseddon** [comment]
I'm closing this pending a PR + lockdown will probably be depreciated
